### ISSUE TITLE
Fontes

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.Sat.Extrato.FastReport#1]
Bom dia @rftd ,

Em primeiro lugar, meus parabéns pelo excelente trabalho, uso o acbr.net.sat a um tempo e quero implementar a impressão ainda essa semana.

Notei que você adicionou as fontes em uma pasta separada, só preciso colocar elas em alguma pasta em específico? Preciso instalar? Existe alguma forma de carregar essa fonte em tempo de execução sem a necessidade de instalar?

Mais uma vez, parabéns!

Abraços

**Comment by rftd** [comment]
A fontes precisam ser instaladas. tem formas de serem instalados no windows por código mas não testei ainda.

**Comment by marcosgerene** [comment]
Achei como instalar via inno setup, vou testar aqui e te dou um retorno

> Source: "D:\Desenvolvimento\AcbrNetSatExtratoFastReports\trunk\Fonts\UbuntuCondensed-Regular.ttf"; DestDir: "{fonts}"; FontInstall: "Ubuntu Condensed-Regular"; Flags: onlyifdoesntexist uninsneveruninstall
