### ISSUE TITLE
Versão do .Sat.Extrato.FastReport defasado

### ISSUE THREAD

**Issue by MrSocrats** [ACBrNet/ACBr.Net.Sat.Extrato.FastReport#11]
A versão do ACBr.Net.Sat que este projeto está utilizando já está defasada. A utilizada é a 1.0.1.4, quando a versão estável atual é a 1.0.1.5. Além disso, aparentemente, há várias discrepancias nas dependencias nos projetos.

Fora que o layout em breve será a versão 0.08.

Esse projeto está descontinuado?

**Comment by rftd** [comment]
Cara este repositório tem apenas o extrato em Fast Reports, como cada pessoa pode usar a sua propria versão do gerador de relatório de acordo com seu sistema não coloquei no nuget e deixei aqui onde cada pessoa pode baixar e usar com sua versão do fast e do sat.
Então se alguém precisar usar tem que baixar e compilar se esta atrasado a versão do sat é so atualizar.
Sobre o Layout 0.08 não estou sabendo sobre a data de obrigatoriedade dela se puder me informar eu posso ver o que posso fazer.

**Comment by MrSocrats** [comment]
Ah, sim, compreendo. Faz sentido, é que apenas aconteceu o acaso de eu utilizar justamente esse projeto para a impressão. Caso queira, acabei atualizando o projeto por conta própria e posso até commitar a versão para esse git.

Então, digo em breve, mas no último documento do SAT(2.23.01), se não li errado, consta que as alterações do layout 0.08 entram em vigor em 01/07/2018. Portanto, não é nenhuma urgencia para o momento.

**Comment by rftd** [comment]
Qualquer contribuição é bem vinda.

**Comment by MrSocrats** [comment]
Tem problema se eu puxar todos os projetos ACBr.Net relacionados para esse repositório? Tive que trazer todos em um só, para adequar todos ao mesmo tempo. 

Claro, posso só deixar as DLLs das referencias, mas aí eu teria que ter permissão para commitar os projetos atualizados em mais 3 repositórios... Fora que talvez você não concorde com as manutenções, mas aí depende mais do senhor do que de mim.

**Comment by rftd** [comment]
Não entendi o que teve que mudar nos outros ?
Qualquer coisa cada projeto tem seu repositorio faça pull request em cada 1 deles que vou analisar.
