### ISSUE TITLE
Layout do extrato mal configurado (?)

### ISSUE THREAD

**Issue by MrSocrats** [ACBrNet/ACBr.Net.Sat.Extrato.FastReport#13]
O extrato, no layout atual, por algum motivo não consegue lidar bem com vendas que possuem vários itens. Por exemplo, se tem +40 itens, na "transição" da primeira para a segunda página algumas informações são duplicados.

Antes disso, ainda faltou configurar o modo de impressão para "split", para permitir impressão de extratos com mais de 30cm. Sem isso, o extrato corta toda a informação depois da primeira página.

Juro que tentei configurar o layout de várias formas, mas não consigo resolver a primeira questão, que é a duplicação de informações de página para página. Abaixo, o problema relatado em imagem:

![img_20171205_101316](https://user-images.githubusercontent.com/22979928/33624541-dcc80e94-d9db-11e7-879d-712255f7c731.jpg)

Provavelmente passei batido por alguma configuração do FastReport, mas não sei bem qual.

**Comment by MrSocrats** [comment]
Só para constar: o problema é na impressão de uma página para outra mesmo. Até cheguei a pensar que seria o caso de não deixar os dados do item "splitarem", mas me deparei com um extrato que teve parte do QR code duplicado.

![img_20171205_165918](https://user-images.githubusercontent.com/22979928/33626217-0ded5ccc-d9e1-11e7-8dd2-f7c2bb2693a4.jpg)

**Comment by MrSocrats** [comment]
Putz, consegui resolver o problema aqui.

O caso é que a impressão no modo split foi um equívoco meu; o modo de impressão default era o correto mesmo. 
O problema era em outro ponto: a configuração do "**UnlimitedHeight**", presente nas propriedades da página. Está como "**true**", o que, a princípio, não parece errado, porque o FR mostra na tela o extrato completo, inclusive quando o conteúdo possui muitos itens. Porém, dessa forma, recai naquele outro ponto em que a impressão não passaria dos 30cm.

A solução foi voltar a configuração "**UnlimitedHeight**" para "**false**" e ajustar a **Page Header** e seus Childs que se repetem em todas as páginas para que só sejam apresentados na primeira página. Além disso, o **DataBand** que apresenta o código de barras e o QR code foi ajustado com o property **CanBreak** para true, que vai evitar eventuais desperdícios de folha com espaços em branco.

O resultado é o seguinte:

![image](https://user-images.githubusercontent.com/22979928/33632618-519d55e4-d9f5-11e7-8d15-f531517bb541.png)
_Nota: aqui eu tive que tirar a margem esquerda do extrato, mas foi por causa de uma particularidade da impressora da Bematech que, por algum motivo, coloca sozinho a margem na esquerda._

Deixarei o .zip do modelo do extrato upado aqui:
[ExtratoSat.zip](https://github.com/ACBrNet/ACBr.Net.Sat.Extrato.FastReport/files/1533131/ExtratoSat.)

**Comment by rftd** [comment]
Olha deve ser algum erro na sua versão do Fast Report pois acabei de testar aqui e não tive erro algum ao gerar um CFe com 50 Itens e não tive problema algum, agora sobre os campos cortados você chegou a instalar as fontes que tem na pasta Fonts ela são necessárias para ficar correto a impressão

**Comment by MrSocrats** [comment]
Desculpe pela demora.

Não sei bem o que ocorre. Refiz alguns testes usando a versão do último commit do projeto, mas não imprime inteiro de forma alguma. 
Sobre as versões do FastReport, a que uso aqui é a 4.5, enquanto a deste projeto é a 4.6. Pode ser que este seja o problema, mas utilizei o mesmo layout em ambas versões e ambas deram o mesmo problema.

É bem capaz de ser alguma particularidade da impressora também. Se realmente for isso, aí não temos muito o que fazer, infelizmente.

Em relação às fontes, realmente eu não havia instalado. Na verdade, nem me atentei que havia um diretório Fonts no projeto keke

Caso queira fechar o issue, pode fechar. Esse problema está mais com cara de ser uma particularidade de configuração da minha parte do que erro do projeto em si.
