### ISSUE TITLE
Exportação para PDF

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.Sat.Extrato.FastReport#2]
Boa tarde @rftd ,

Continuando os testes tive problema com a exportação para PDF.

Repare nos arquivos "Envio" e "Cancelamento" eu mandei para uma impressora de PDF e salvei, funcionou perfeitamente.
Agora se eu salvar diretamente pelo componente os códigos de barras e o fundo do logotipo fica preto.

[35161011111111111111591234567890000939609870.pdf](https://github.com/ACBrNet/ACBr.Net.Sat.Extrato.FastReport/files/520020/35161011111111111111591234567890000939609870.pdf)
[35161011111111111111591234567890000942410884.pdf](https://github.com/ACBrNet/ACBr.Net.Sat.Extrato.FastReport/files/520021/35161011111111111111591234567890000942410884.pdf)
[cancel.pdf](https://github.com/ACBrNet/ACBr.Net.Sat.Extrato.FastReport/files/520019/cancel.pdf)
[envio.pdf](https://github.com/ACBrNet/ACBr.Net.Sat.Extrato.FastReport/files/520022/envio.pdf)

---

Sobre o logotipo: mesmo passando NULL para o logotipo o logo do acbr saiu na impressão, isso acontece por estar em ambiente de testes ou é alguma falha?

Abraços

**Comment by rftd** [comment]
cara sobre a exportação em PDF deve ter algo errado ai na sua maquina pois aqui exportei corretamente tanto pelo componente quanto pelo preview sem erro.
O logo no caso se for null ele imprime o do ACBr mesmo, não  foi erro so não foi previsto imprimir sem logo.

**Comment by marcosgerene** [comment]
[img013.pdf](https://github.com/ACBrNet/ACBr.Net.Sat.Extrato.FastReport/files/520140/img013.pdf)

Esse é o resultado de como está o meu (uso o ACBr), e como vai ficar quando eu migrar para a nova versão...

Quanto ao logo, seria interessante imprimir sem ele trambém.

Outra coisa: no acbr a uns 6 meses mandei uma alteração aqui que permite ao usuário definir um espaço no final da folha para que ao puxar o papel não corte em cima do QRCode, seria interessante ter essa opção também.

PS: tem como acionar a guilhotina da impressora via fastreports ou somente via escpos?

Abraços

**Comment by rftd** [comment]
Não entendi a comparação você quer sugerir alguma modificação ?
Impressão sem logo já implementa logo subo um update
Sim é possivel adicionar algo.
A guilhotina apenas por ESC/POS, tem planos futuros de implementar mas a falta de hardware me complica neste caso.

**Comment by marcosgerene** [comment]
Seria interessante ter uma propriedade "espaço final" com o tamanho do footer em branco, para que ao terminar de imprimir pulasse um pouco de papel evitasse que o usuario corte o papel em cima do qr-code

**Comment by rftd** [comment]
Eu vi uma diferença entre as datas nos duas impressões foi o mesmo CFe ?
Teria como me passar este CFe para conferir o por que da diferença ?

**Comment by rftd** [comment]
Eu adicionei a propriedade espaço final ao extrato.
