### ISSUE TITLE
Dúvida Extrato Resumido

### ISSUE THREAD

**Issue by otavioreis** [ACBrNet/ACBr.Net.Sat.Extrato.FastReport#24]
Bom dia, na verdade não é um problema, mas uma dúvida mesmo...

Vocês chegaram a implementar um extrato resumido, ou apenas o completo mesmo?

Desde já agradeço a atenção.

Atenciosamente,
Otávio A. Reis

**Comment by rftd** [comment]
Tem as 2 versões.
