### ISSUE TITLE
Problema ao imprimir

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.Sat.Extrato.FastReport#4]
Estou com um problema para imprimir um SAT em um cliente

> Value cannot be null. Parameter name: encoder

Entretanto o cupom está transmitido e cancelado, tentei 3 vezes e falhou nos 3.

Segue os cupons:
[sat.zip](https://github.com/ACBrNet/ACBr.Net.Sat.Extrato.FastReport/files/683010/sat.zip)

PS: testei carregando o xml e mandando imprimir pelo demo e foi. Em outros clientes não tenho este problema =S

Meu código:

```
var _acbrCfe = CFe.Load(pathXML);

var extrato = this.GetExtrato();

extrato.Filtro = ExtratoFiltro.Nenhum;
extrato.LayOut = ExtratoLayOut.Completo;
extrato.Logo = Globals.DadosEmpresa.LogotipoNFe;
extrato.MostrarPreview = false;
extrato.MostrarSetup = false;
extrato.DescricaoUmaLinha = false;
extrato.NumeroCopias = 1;
extrato.PrinterName = ConfigLocal.ImpressoraTermica.NomeImpressora;
extrato.Site = Globals.SiteGereneSI;
extrato.SoftwareHouse = "GERENE SI";
extrato.EspacoFinal = (float)(ConfigLocal.ImpressoraTermica.EspacoFinal / (decimal)(96 / 25.4));
extrato.ImprimirExtrato(_acbrCfe);
```

**Comment by rftd** [comment]
Este erro acontece na chamada da impressão ?

**Comment by marcosgerene** [comment]
Estou tentando analisar o caso ainda, não acontece no meu computador, vou ter que pegar o banco de dados e o sat do cliente pra testar provavelmente

**Comment by marcosgerene** [comment]
@rftd,

Removi o logotipo e deu certo, deve ter algo errado com meu sistema, vou fechar a insue, se achar algo errado no meio dos meus testes reabro.

Obrigado

**Comment by marcosgerene** [comment]
O meu sistema passa um objeto do tipo Bitmap para o extrato. Quais os formatos aceitos? estou passando um png.

public Bitmap LogotipoNFe { get; set; }

**Comment by rftd** [comment]
formato não é o problema deve estar dando algo errado na função de converter a imagem em byte array.
Vou investigar.

**Comment by marcosgerene** [comment]
@rftd ,

Testei a mesma imagem pelo demo e funcionou, porem se eu passar o mesmo objeto de imagem para a impressão da nfe/nfce/mdfe do projeto do adenilton a impressão sai ok e se eu exportar a imagem também exporta, fiquei sem entender o pq deu certo no demo.

Alguma dica?
