### ISSUE TITLE
Endereço do emitente

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.Sat.Extrato.FastReport#6]
Nas duas impressões o endereço do emitente seria necessário ter pelo menos duas linha, está cortando na maioria dos clientes mesmo com a fonte ubuntu.

Tentei mexer na minha maquina, até deu certo, ia fazer o pull request mas mudou varias outras coisas quando mandei comparar o arquivo, deve ser a versão do fast reports, então fiquei com medo de "quebrar" o que funciona, teria como vc aumentar um pouco o endereço (2 linhas)?

Obrigado

**Comment by rftd** [comment]
Sim eu modifico assim que tiver um tempo aqui eu mudo.
