### ISSUE TITLE
Erro de referencias ou somente falta alguma coisa enfim, não compila 

### ISSUE THREAD

**Issue by robertorp** [ACBrNet/ACBr.Net.Sat.Extrato.FastReport#8]
![screen-15 15 11 13 02 2017](https://cloud.githubusercontent.com/assets/10251705/22894184/41182ade-f1ff-11e6-9e19-ffd0494d13eb.png)

ai somente queria saber de onde é isso?
olhei nas referencias e aparentemente ta tudo ok.. olhando somente

**Comment by rftd** [comment]
Provavelmente sua versão do FastReports e diferente da usada na biblioteca e não tem estas opções.
Você pode simplesmente comentar e usar normalmente.

**Comment by robertorp** [comment]
Dentro do projeto não vem o fast por padrão não? porque simplesmente mandei ele compilar.. não referenciei dlls manualmente, ou seja as que veio no projeto, anão ser que deu concidencia de min ter alguma perdida no pc e ele pegou do mesmo local, mas troquei as dll aqui e deu certo. 

Vlw

**Comment by rftd** [comment]
AS vezes você tem no GAC alguma versão do FastReport e ele pegou de la a referencia.
