### ISSUE TITLE
Não consigo imprimir, digo ele não diz nada.. não da erro.. simplesmente não acontece nada

### ISSUE THREAD

**Issue by robertorp** [ACBrNet/ACBr.Net.Sat.Extrato.FastReport#9]
Não consigo imprimir, digo ele não diz nada.. não da erro.. simplesmente não acontece nada, ele aparece a progressbar de impressão do fastreport rapidamente, mas não da erro não acontece nada, ai queria uma dica se possível

**Comment by rftd** [comment]
já tento ver se o preview aparece ?

**Comment by vitormoreiradematos** [comment]
Estou com o mesmo problema, acho q deve ser algo na configuração da impressora tipo um arquivo com o nome ou a porta.
Conseguiu resolver? Se sim me ajuda a resolver.
agradeço desde já!

**Comment by rftd** [comment]
Para imprimir o relatório precisa instalar a impressora como impressora do windows, ele não é impresso direto para porta da impressora.
Tenho planos de no futuro fazer uma versão escpos mas preciso primeiro adquirir uma impressora.

**Comment by vitormoreiradematos** [comment]
Consegui passei o nome da impressora e o numero de copias.
Agora estou com outra duvida como editar o relatorio no fast report tipo a largura dos campos  ordem ou o tamanho. Tem algum arquivo de design ou de parametros na construção do relatorio para e editar?

**Comment by robertorp** [comment]
Não tinha conseguido, estou usando o ACBRMonitor para isso. Já usava ele para várias coisas e tenho uma implementação dele fácil de fazer imprimir então optei por ele.

**Comment by vitormoreiradematos** [comment]
Era só passar o nome da impressora e o numero de copias igual a 1.
No ACBRMonitor ele permite eu modificar meus relatorios tipo fontes, tamanho , posição? Se sim como vc faz?
